package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import appoint.entity.Doctor;
import appoint.entity.Hospital;
import appoint.entity.Scheduling;
import appoint.entity.UnlineOrder;

import greendao.DoctorDao;
import greendao.HospitalDao;
import greendao.SchedulingDao;
import greendao.UnlineOrderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig doctorDaoConfig;
    private final DaoConfig hospitalDaoConfig;
    private final DaoConfig schedulingDaoConfig;
    private final DaoConfig unlineOrderDaoConfig;

    private final DoctorDao doctorDao;
    private final HospitalDao hospitalDao;
    private final SchedulingDao schedulingDao;
    private final UnlineOrderDao unlineOrderDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        doctorDaoConfig = daoConfigMap.get(DoctorDao.class).clone();
        doctorDaoConfig.initIdentityScope(type);

        hospitalDaoConfig = daoConfigMap.get(HospitalDao.class).clone();
        hospitalDaoConfig.initIdentityScope(type);

        schedulingDaoConfig = daoConfigMap.get(SchedulingDao.class).clone();
        schedulingDaoConfig.initIdentityScope(type);

        unlineOrderDaoConfig = daoConfigMap.get(UnlineOrderDao.class).clone();
        unlineOrderDaoConfig.initIdentityScope(type);

        doctorDao = new DoctorDao(doctorDaoConfig, this);
        hospitalDao = new HospitalDao(hospitalDaoConfig, this);
        schedulingDao = new SchedulingDao(schedulingDaoConfig, this);
        unlineOrderDao = new UnlineOrderDao(unlineOrderDaoConfig, this);

        registerDao(Doctor.class, doctorDao);
        registerDao(Hospital.class, hospitalDao);
        registerDao(Scheduling.class, schedulingDao);
        registerDao(UnlineOrder.class, unlineOrderDao);
    }
    
    public void clear() {
        doctorDaoConfig.clearIdentityScope();
        hospitalDaoConfig.clearIdentityScope();
        schedulingDaoConfig.clearIdentityScope();
        unlineOrderDaoConfig.clearIdentityScope();
    }

    public DoctorDao getDoctorDao() {
        return doctorDao;
    }

    public HospitalDao getHospitalDao() {
        return hospitalDao;
    }

    public SchedulingDao getSchedulingDao() {
        return schedulingDao;
    }

    public UnlineOrderDao getUnlineOrderDao() {
        return unlineOrderDao;
    }

}
